### PR TITLE
Nextprevsib

### PR DESCRIPTION
**Pull request by asurkov**
simple navigation, minimal port of https://wiki.mozilla.org/Accessibility/WebAccessibilityAPI#Content_traversal

### CODE REVIEW

**Comment by marcoscaceres** [comment]
This change set seems to include the previous change set where the "element" rename was done. Let's merge the other first.

**Comment by marcoscaceres** [comment]
I'm going to review this one tomorrow

**Comment by asurkov** [comment]
right, that I started that branch on top of previous branch. Is it ok
practice or should I do differently?

**Comment by marcoscaceres** [comment]
For new features, always start a new branch from gh-pages. That gives us a clean view of what's changed.

**Comment by asurkov** [comment]
those should be fairly independent then which might be hard for consequent
work. A branch on top of a branch approach doesn't work?

**Comment by marcoscaceres** [comment]
On June 12, 2015 at 1:11:20 PM, Alexander Surkov (notifications@github.com) wrote:

> those should be fairly independent then which might be hard for consequent
> work. A branch on top of a branch approach doesn't work?

Branch on top of another branch works too. The only minor thing is making sure they are merged in the right order (or that base branch does not change). That's just to keep clarity in the Pull Request about what feature is being added.

**Pull request merged**
